---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: relay-secrets
  namespace: relay
spec:
  encryptedData:
    database_url: AgAjjczBOjbdm6lbsrDPpH+UOOlDd7Xb68FK5mGNdAYKbu1ddgsRg+copFg6GEspKnS5zSUZYziaQlgGG6APCyNio2ed76/FvUgPbl7F1EslgVDBo5PrqO3DWg3xETtNQt4B6MVXriPjlIt7fa5L8M9XNl8I9vtGJH7eP+cuLFJA1Isu7RduDArC1umNj6xPlZArr1MoTa/3pm++TLT6ng2w9i4ekdQevHK46146/mLwiF878nblvLc1wzndcDLcB0XCQkDUpWfZn8Fdf3L4s5ayAZ9dPSyMamkQcM5l8lq9LMbebvbHrieuMQaAmBu4ESeXH+JAQpm7sSq2CJ/1FGbxxkyFSGq2w/9/6cFEe1Nzgc1sPr/xOuPtz5MOCwu975//NP7NZhaGOawbZKmd+O2fBFckIRnDAsufQLUazyU8E4/gs4vXj7lFjc0Hqg5jFWduBJX0nj+iHDL55gTzqlMxhA85l3loWutq3awvD05OCevKu5l7482KD9+nA7BCqfd9yLm7R9pGIqkDk/Jyn7Bf0/E1GRGOTvI3UKYE8a5L9opcwYJSQzsVpYc4I5A6IKGexnXPYDWZqIb7AhxYbv+zUtrF78sxZt8hgOuQp7R2VfFtrUTRG1xvOViKS1OrwpUKAqriqfCtg05Et4B6Wb+69jwBkTN3cr+2X/Xs2KkJ346PHKG9Awxrrin5suXSfG2hCoqorEhpN23KJW4fuJN3Fu24DrFGiuhqdVhto1nuyLwRUOk8a/VdbzaMeujXbD53wpQifSLj7XOdjreewdm9labAiVsInyxmBFBIUZ+sbwhKCha1ByfXox3gcgOnxrBq6dKjPHej/V/TOXnHixdyjbcvkyYtAg==
  template:
    metadata:
      name: relay-secrets
      namespace: relay
